openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Swagger UI CloudHaven API Docs"
  description: "Documentation for CloudHaven API and supported options"
paths:
  /api/start-vendor-app/{vendorId}:
    get:
      tags:
        - "CloudHaven Backend (http://localhost:5000)"
      summary: "Pings /start-app endpoint for given vendorid vendor app"
      responses:
        500:
          description: "Unknown Error Occurs"
        400:
          description: "No Vendor ID Provided or Not Found"
        200:
          description: "OK"
      parameters:
        - name: vendorId
          in: path
          required: true
          description: "ID of the vendor app we are looking to 'start'."
          schema:
            type: string or int
  /start-app:
    get:
      tags:
        - "Vendor App Backend"
      summary: "Retrieves the base JSON for the given Vendor App"
      responses:
        200:
          description: "OK, Response includes index page json object of interest. Components is array of any given number of supported components"
          content:
            application/json:
              schema:
                type: object
                properties:
                  vendorid:
                    type: integer
                    description: "vendor's id"
                    example: 1
                  vendorauth:
                    type: string
                    description: "vendor's password/auth token"
                  components:
                    type: object
                    description: "Components that will be rendered in ui"
                    properties:
                      component:
                        type: string
                        description: "name of component to render"
                        example: "form, card, button, link, image, text, table"
                      title:
                        type: string
                        description: "title of component"
                      description:
                        type: string
                        description: "description of component"
                      header:
                        type: string
                        description: "header of card"
                        example: "Card option"
                      body:
                        type: string
                        description: "body of card"
                        example: "Card option"
                      footer:
                        type: string
                        description: "footer of component"
                        example: "Card option"
                      text:
                        type: string
                        description: "text of button"
                        example: "button option"
                      submit_location:
                        type: url
                        description: "where to submit button"
                        example: "button option"
                      src:
                        type: url
                        description: "url for link or image"
                        example: "link or image option"
                      alt:
                        type: string
                        description: "alternative text for link or image"
                        example: "link or image option"
                      fields:
                        type: object
                        description: "fields to be rendered in component if applicable"
                        properties:
                          child:
                            type: string
                            description: "child component to be rendered, can be text or textField"
                            example: "text || textField"
                          match:
                            type: regex
                            description: "For authenticating (optional)"
                          required:
                            type: boolean
                            description: "toggle to make field required"
                          sensitive:
                            type: boolean
                            description: "toggle for case sensitivity"
                          label:
                            type: string
                            description: "string label for field"
                          


